### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pawurb** [pawurb/pg-extras-rs#4]
- [ ] web UI flash messages
- [ ] web UI http basic
- [ ] detect missing foreign key indexes
- [ ] web UI pluggable to any axum app (via nested router)
- [ ] customize diagnose alert conditions
- [ ] kill by pid feature (for long running queries)
